### ISSUE TITLE
Please clarify license for highlighFade plugin

### ISSUE THREAD

**Issue by mjherzog** [blairmitchelmore/jquery.plugins#1]
We are interested to know the license for your older highlightFade plugin from: https://web.archive.org/web/20070218124137/http://jquery.offput.ca/highlightFade/. Would it be WFTPL like the other plugins here? Thank you.

**Comment by bmitchelmore** [comment]
@mjherzog Yeah, it's WTFPL. Go ham with it.

**Comment by mjherzog** [comment]
Blair,

Thank you very much for the quick answer!

Regards, Michael

Michael J Herzog
Mobile +1 650 380 0680 - Pacific Time
AboutCode at https://github.com/nexB
DejaCode    at https://enterprise.dejacode.com/landing/
nexB Inc.     at https://www.nexb.com

CONFIDENTIALITY NOTICE:  This e-mail (including attachments) may contain
information that is proprietary or confidential. If you are not the
intended recipient or a person responsible for its delivery to the intended
recipient, do not copy or distribute it. Please permanently delete the
e-mail and any attachments, and notify us immediately at (650) 380-0680.
